mim-117: skilj pa arenden som kommer fran webben och internt
Bostads-AB-Mimer/onecore-odoo pull request #69
Opened 2024-10-22 13:25 UTC by lalmqvist

2024-10-22 14:00 UTC, henrikhenrikpersson commented on onecore_maintenance_extension/views/maintenance_views.xml
> +                            <span invisible="creation_origin == 'internal'">Från Mimer.nu</span>
Kanske nice att ha `invisible="creation_origin != 'mimer-nu'"` ifall att det eventuellt läggs till fler ställen som ärenden kan komma från?

2024-10-22 14:01 UTC, henrikhenrikpersson requested changes
Ser bra ut! 🙌 Ett par små kommentarer bara!

2024-10-23 12:38 UTC, lalmqvist commented on onecore_maintenance_extension/views/maintenance_views.xml
> +                            <span invisible="creation_origin == 'internal'">Från Mimer.nu</span>
Klokt 👍

2024-10-23 12:38 UTC, lalmqvist commented on onecore_maintenance_extension/views/maintenance_views.xml
> +                            <span invisible="creation_origin == 'mimer-nu'">Skapad intert</span>
Snyggt fångat!

2024-10-23 12:42 UTC, henrikhenrikpersson approved these changes

2024-10-23 12:46 UTC, johanneskarlsson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Ska man kunna sätta den här själv? Jag tänker att man kan titta på notisen som dyker upp i loggen för ärendet. Om den inte är skapad av mimer.nu-användaren är den skapad internt?

2024-10-23 13:04 UTC, johanneskarlsson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Eller, lite enklare, titta vem som skapade ärendet med hjälp av create_uid i för ärendet 😅

2024-10-23 13:24 UTC, lalmqvist commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Det låter ju klokt, men det förutsätter att usern från mimer.nu har samma id i varje miljö?

2024-10-23 13:28 UTC, henrikhenrikpersson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Kan vi köra `internal` som default, och annars skicka med `mimer-nu` från onecore-core?

2024-10-23 13:30 UTC, johanneskarlsson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Ja, om du utgår från create_uid direkt, men om du kollar om usern har "odoo@mimer.nu" som login så är det samma överallt 🙂

2024-10-23 13:33 UTC, johanneskarlsson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Jag gör något liknande här https://github.com/Bostads-AB-Mimer/onecore-odoo/blob/66bdeb8ee43cca0ec14054ebf7a34ea45a4d1dae/onecore_maintenance_extension/models/maintenance.py#L108

2024-10-23 13:41 UTC, johanneskarlsson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Du borde bara kunna göra något sånt här: 

```    
    creator_login = fields.Char(compute='_compute_creator_login', string='Creator Login')

    def _compute_creator_login(self):
        for record in self:
            if record.create_uid:
                record.creator_login = record.create_uid.login
            else:
                record.creator_login = False```

2024-10-23 13:43 UTC, johanneskarlsson commented on onecore_maintenance_extension/models/maintenance.py
> +    creation_origin=fields.Selection([('mimer-nu', 'Mimer.nu'), ('internal', 'Internt')], string='Skapad från', default='internal', store=True)
Säger chatGPT 😅

2024-10-23 14:01 UTC, merged